-
  # 配置文件描述
  name: 通用配置
  # 配置文件名
  file: config.yaml
  # 视图信息
  view:
    -
      key: 统计状态
      comment: 是否统计状态 关闭后可降低redis压力...
      path: 'status'
      type: 'boolean'
    -
      key: 全部更新转发
      comment: 全部更新是否使用转发
      path: 'forward'
      type: 'boolean'
    -
      key: 重启配置
      path: 'pm2'
      type: 'group'
      part:
        -
          key: 重启是否调用pm2
          comment: 重启是否调用pm2 如果不调用则会直接关机 此配置适合有进程守护的程序
          path: 'pm2.enable'
          type: 'boolean'
        -
          key: 调用pm2指令
          comment: 调用pm2指令 如使用不同的包管理器请自行修改
          path: 'pm2.cmd'
          type: 'text'
    -
      key: 更新完成自动重启
      comment: 更新完成是否自动重启
      path: 'restart'
      type: 'boolean'
